name: Main build pipeline

run-name: ${{ inputs.run_name }}
on:
  workflow_dispatch:
    inputs:
      run_name:
        description: 'Name of the current pipeline run'
        required: false
        type: string
      labels:
        description: 'List of labels'
        required: true
        default: ''

jobs:
  validate:
    container:
      image: python:3.10-alpine
    runs-on:
      - self-hosted
      - k8s-api
      - linux-amd64-m
    outputs:
      prs_urls: ${{ steps.list_prs.outputs.prs_urls }}
      repos: ${{ steps.list_prs.outputs.repos }}
    steps:
      - name: List Pull Requests
        uses: Hitachi-Astemo-SDV/github-hitachi-astemo-poc-common-actions/actions/list-prs@list_prs
        id: list_prs
        with:
          GITHUB_TOKEN: ${{ secrets.BUILD_GH_TOKEN }}
          labels: ${{ inputs.labels }}

      - name: Print Pull Requests
        run: echo "${{ steps.list_prs.outputs.prs_urls }}"
